clang++ \
-std=c++2a \
src/main.cc \
/usr/local/Cellar/gumbo-parser/0.10.1/lib/libgumbo.dylib \
/usr/local/Cellar/sfml/2.5.1/lib/libsfml-graphics.dylib \
/usr/local/Cellar/sfml/2.5.1/lib/libsfml-network.dylib \
/usr/local/Cellar/ossp-uuid/1.6.2_2/lib/libuuid.dylib \
/usr/local/Cellar/sfml/2.5.1/lib/libsfml-window.dylib \
/usr/local/Cellar/sfml/2.5.1/lib/libsfml-system.dylib \
/usr/local/Cellar/curl/7.74.0/lib/libcurl.dylib \
/usr/local/Cellar/libuv/1.40.0/lib/libuv.dylib \
-I/usr/local/Cellar/gumbo-parser/0.10.1/include \
-I/usr/local/Cellar/ossp-uuid/1.6.2_2/include \
-I/usr/local/Cellar/libuv/1.40.0/include \
-I/usr/local/Cellar/curl/7.74.0/include \
-I/usr/local/Cellar/sfml/2.5.1/include \
-o main